### ISSUE TITLE
Update version in Composer

### ISSUE THREAD

**Issue by ockam** [jimbojsb/craft-db-snapshot#3]
The version property in `composer.json` is still at 1.0.0. The update doesn’t show in Craft.

**Comment by edmotech** [comment]
Yes, please release 1.1.0. I was able to get it working using the master branch but would love to use an actual release.

**Comment by simeon-smith** [comment]
Yes, please release 1.1.0. I was able to get it working using the master branch but would love to use an actual release.

**Comment by jimbojsb** [comment]
Released as 1.1.1. It was tagged the day I merged this, but I'm not sure how that version got into composer.json, must have been stubbed out. Fixed now.
